### PR TITLE
Directory cleanup

### PR DESCRIPTION
**Pull request by mdlewisfb**
Pull request for cleaning up some of the directory naming and such.
Changed src/Devices/ to src/devices/ for consistent directory naming, and updated the test makefile that pointed to both "Devices/" and "devices/"
Also consolidated the inc/ directories (common/inc and inc/) to all be under inc/, updated the include commands throughout the code that needed it and the CCS project. Tested these changes in Windows for both Unit Tests and build, as well as Linux Unit Tests.

@vthakur7f and @markhor not sure if this last change of the common/inc is something we want? I can revert it back, if not.

Also, I want to delete "config/oc-sdr/config.c" since it is an empty file, is there any reason not to?

Lastly, do we have file naming guidelines for the repo? Seem to be mix of capitalizations, camel cases, underlines, etc. Might be nice to pick how we want to do it and I can clean those up here, too, or in a later PR?

### CODE REVIEW

**Comment by vthakur7f** [comment]
Thanks, @mdlewisfb for taking an initiative to start a clean up for the directory structure and the file names. 
As of now, we don't have any file naming scheme which has been followed. We can open that discussion and finalize it. Also looks like I missed adding a coding guideline files. I will do add that later. 
Regarding your common/inc folder movement. I think it's better if we can revert this commit for now as this folder shared with the host code( for supporting common schema approach). I know it's name is little confusing with inc/common ( which has files that are commonly used within the EC firmware.) but we can use something else as a folder name no issues with that. We can revisit this folder structure back again when we have build environment ready for the OC and if required we could move these files to some place where we could easily make out that these are shared files between Host and EC firmware. 

"config/oc-sdr/" This folder was for the config files. I think we have pull request pending for approval. So It's up to you if you want to delete it now and then with the pull request whenever it's getting approved we can have this folder back again.

**Comment by mdlewisfb** [comment]
I get why it was common/inc, I just don't like it as it's not necessary and not all folders in there seem to be used by the host software anyway - which btw doesn't seem to be in this repo? I was looking for the makefile to update the path but didn't see it. 
I can change it back if we decide we are going to live with it, but I don't like holding off on changes we are going to make in the future. It would be better to make all the structural changes now so that going forward all pull requests will be able to use the same foundation, rather than going back and modifying stuff and then having the result be a bunch of merge conflicts caused by file renaming/restructuring.

What's the planned usage difference between config/oc-sdr and platform/oc-sdr/cfg? 

Ok if guidelines don't exist I'll create an issue to make one.

**Comment by vthakur7f** [comment]
> I get why it was common/inc, I just don't like it as it's not necessary and not all folders in there seem to be used by the host software anyway - which btw doesn't seem to be in this repo? I was looking for the makefile to update the path but didn't see it.
>>We still need to add host application to this repo. It will be done within a day or two. Yes, the makefile is only including global folder, platform but internally schema file is using all the ocmw wrapper header files.  
 
> I can change it back if we decide we are going to live with it, but I don't like holding off on changes we are going to make in the future. It would be better to make all the structural changes now so that going forward all pull requests will be able to use the same foundation, rather than going back and modifying stuff and then having the result be a bunch of merge conflicts caused by file renaming/restructuring.
>> yes it's perfectly ok to change the directory structure only thing we have to keep in mind that we don't break anything when we are using already existing CCS and other build tools. My personal opinion was to keep the shared file between host and EC at one place but that's not necessarily the final option we have.   

> 
> What's the planned usage difference between config/oc-sdr and platform/oc-sdr/cfg?
> I dont really remeber it but I think intention of having config/oc-sdr was same as of platform.oc-sdr/cfg.  So one of these can be removed.

> Ok if guidelines don't exist I'll create an issue to make one.
>> These exist but I need to just merege them to TIP repo.

**Comment by mdlewisfb** [comment]
Sorry, meant file naming conventions not guidelines on that last line. Understood that you are adding the coding guidelines to the TIP repo. 

I verified the changes with CCS (just one line to point from common/ to inc/) so that's not a problem. 

The schema itself is defined in the firmware repo though, I understand wanting everything under common/ so that external libraries don't need knowledge of the firmware internal structure and are able to use common definitions, but the way it has been used so far it doesn't seem to have achieved that. ::shrug:: 

I just want to keep moving on stuff so will revert to the first commit which is only Devices->devices and take this discussion out of this PR.

**Pull request merged**
